apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: record-platform
  labels: { app: analytics-service }
spec:
  selector: { app: analytics-service }
  ports:
    - name: http
      port: 4004
      targetPort: http
