apiVersion: v1
kind: Service
metadata:
  name: records-service
  namespace: record-platform
  labels: { app: records-service }
spec:
  selector: { app: records-service }
  ports:
    - name: http
      port: 4002
      targetPort: http
