apiVersion: v1
kind: Service
metadata:
  name: python-ai-service
  namespace: record-platform
  labels: { app: python-ai-service }
spec:
  selector: { app: python-ai-service }
  ports:
    - name: http
      port: 5005
      targetPort: http
