apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: record-platform
  labels: { app: kafka }
spec:
  selector: { app: kafka }
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka