- op: remove
  path: /spec/template/spec/containers/0/command
- op: replace
  path: /spec/template/spec/containers/0/args
  value: ["-u","pgbouncer","/etc/pgbouncer/pgbouncer.ini"]
- op: replace
  path: /spec/template/spec/containers/0/image
  value: edoburu/pgbouncer:1.22.1
- op: add
  path: /spec/template/spec/containers/0/securityContext
  value:
    runAsUser: 100
    runAsGroup: 100
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
