- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
  value: /_ping
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
  value: /_ping
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
  value: 90
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
  value: 10
