# infra/k8s/overlays/dev/patches/probes-auth.jsonpatch.yaml
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
  value: /healthz
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
  value: /healthz

- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
  value: http
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/port
  value: http

- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
  value: 20
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
  value: 30
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
  value: 10
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
  value: 10
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/periodSeconds
  value: 5
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
  value: 5
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
  value: 2
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
  value: 2
