apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: record-platform
  labels: { app: nginx }
spec:
  replicas: 1
  selector: { matchLabels: { app: nginx } }
  template:
    metadata:
      labels: { app: nginx }
    spec:
      containers:
        - name: edge
          image: nginx:1.27-alpine
          ports:
            - { name: http,  containerPort: 8080 }
            - { name: perf,  containerPort: 8082 }
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 10
          volumeMounts:
            - name: nginx-cm
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-cm
          configMap:
            name: nginx-cm
            items:
              - key: nginx.conf
                path: nginx.conf
