apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config
  - postgres
  - pgbouncer
  - redis
  - exporters
  - monitoring
  - observability
  - haproxy
  - nginx
  - api-gateway
  - auth-service
  - records-service
  - listings-service
  - analytics-service
  - python-ai-service
  - social-service
  - auction-monitor        # NEW (you added this)
  - cron-jobs              # NEW (you added this)
  - kafka                  # (recommended dev Kafka)
