apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-config.yaml
  - app-secrets.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: proto-files
    files:
      - auth.proto=proto/auth.proto
      - records.proto=proto/records.proto
