apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - otel-collector-deploy.yaml
  - jaeger-deploy.yaml
  - grafana-dashboards.yaml
  - servicemonitors.yaml
  - podmonitors.yaml

# Note: newrelic-secret.yaml is optional - create it manually if using New Relic
# kubectl create secret generic newrelic-secret --from-literal=license-key='YOUR_KEY' -n observability

