apiVersion: v1
kind: Service
metadata:
  name: social-service
  namespace: record-platform
  labels: { app: social-service }
spec:
  selector: { app: social-service }
  ports:
    - name: http
      port: 4006
      targetPort: http
    - name: grpc
      port: 50056
      targetPort: grpc

